[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
; ESP32-S3-WROOM-1-N16R8: 16MB quad flash + 8MB octal PSRAM
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
build_flags = -DBOARD_HAS_PSRAM
monitor_speed = 115200
upload_port = COM10
monitor_port = COM10

; Add CAN-related libraries here later if needed.
; lib_deps =
;     https://github.com/miwock/ESP32CAN

lib_deps =
    ayushsharma82/ElegantOTA @ ^3.1.6
