[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Add CAN-related libraries here later if needed.
; lib_deps =
;     https://github.com/miwock/ESP32CAN

lib_deps =
    ayushsharma82/ElegantOTA @ ^3.1.6
